[project]
name = "local-learn"
version = "0.1.0"
description = ""
authors = [
    {name = "anhnt226",email = "tien226anh@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "pyqt6 (>=6.10.1,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyinstaller (>=6.17.0,<7.0.0)",
    "watchdog (>=6.0.0,<7.0.0)"
]
